"""
utils/passport.py
─────────────────
Phase 4 — Creative Ownership Intelligence.

Builds a Creative Passport PDF entirely in memory using ReportLab and
returns the raw bytes.  No file is written to disk inside this function.

The caller (views/view_project.py) is responsible for:
  - Offering the bytes via st.download_button
  - Stamping project.passport with exported_at / watermark_id
  - Logging the passport_exported timeline event
  - Calling save_project()

build_passport_pdf() is pure: no side effects, no Streamlit imports.
"""

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
)


# ── Palette — matches the app's dark-mode accent colours ─────────────────────
_GREEN  = colors.HexColor("#1DB954")
_PURPLE = colors.HexColor("#8B5CF6")
_BLUE   = colors.HexColor("#3B82F6")
_LIGHT  = colors.HexColor("#C4C4C8")
_MUTED  = colors.HexColor("#A1A1AA")
_DARK   = colors.HexColor("#18181B")
_WHITE  = colors.HexColor("#FAFAFA")

# Default transparency statement used when no human-approved text exists yet.
_DEFAULT_TRANSPARENCY = (
    "This Creative Passport was generated by HarmonyLedger. "
    "The contribution percentages are computed deterministically from the "
    "project timeline log using Methodology v{version}. "
    "Section authorship is derived from each section's provenance field "
    "(human_written = 100% human; ai_generated = 100% AI; "
    "ai_then_human = 50/50). "
    "The direction score counts human creative decisions "
    "(lock, unlock, regenerate, accept, reject, human edit) as a fraction "
    "of all timeline events."
)


def build_passport_pdf(project) -> bytes:
    """Build a Creative Passport PDF for *project* and return raw bytes.

    Args:
        project: A Project instance (utils.models.Project).

    Returns:
        bytes — the PDF content starting with b'%PDF'.

    Does not mutate *project* or call save_project().
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=22 * mm,
        bottomMargin=22 * mm,
        title=f"Creative Passport — {project.name}",
    )

    styles = getSampleStyleSheet()
    story  = []

    # ── Styles ────────────────────────────────────────────────────────────────
    h1 = ParagraphStyle(
        "h1", parent=styles["Heading1"],
        fontSize=20, textColor=_WHITE, spaceAfter=2,
    )
    h2 = ParagraphStyle(
        "h2", parent=styles["Heading2"],
        fontSize=12, textColor=_BLUE, spaceBefore=10, spaceAfter=4,
    )
    body = ParagraphStyle(
        "body", parent=styles["Normal"],
        fontSize=9, textColor=_LIGHT, leading=14,
    )
    muted = ParagraphStyle(
        "muted", parent=styles["Normal"],
        fontSize=8, textColor=_MUTED, leading=12,
    )
    label_style = ParagraphStyle(
        "label", parent=styles["Normal"],
        fontSize=8, textColor=_MUTED, leading=11,
    )
    value_style = ParagraphStyle(
        "value", parent=styles["Normal"],
        fontSize=9, textColor=_WHITE, leading=12,
    )

    # ── Header ────────────────────────────────────────────────────────────────
    song    = project.song or {}
    title   = song.get("title") or project.name
    genre   = song.get("genre", "")
    mood    = song.get("mood", "")
    tempo   = song.get("tempo", "")
    key     = song.get("key", "")
    time_sig = song.get("time_signature", "")

    story.append(Paragraph("🛂  Creative Passport", h1))
    story.append(Paragraph(title, ParagraphStyle(
        "songtitle", parent=styles["Normal"],
        fontSize=16, textColor=_GREEN, spaceAfter=4, fontName="Helvetica-Bold",
    )))

    meta_parts = [p for p in [genre, mood, tempo, key, time_sig] if p]
    if meta_parts:
        story.append(Paragraph("  ·  ".join(meta_parts), muted))

    story.append(Spacer(1, 4 * mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=_MUTED))
    story.append(Spacer(1, 3 * mm))

    # ── Contribution Numbers ──────────────────────────────────────────────────
    story.append(Paragraph("Contribution Split", h2))

    contrib        = project.contribution or {}
    human_pct      = contrib.get("human_pct", 0.0)
    ai_pct         = contrib.get("ai_pct", 0.0)
    dir_score      = contrib.get("direction_score", 0.0)
    meth_version   = contrib.get("methodology_version", 1)
    computed_at    = contrib.get("computed_at", "—")

    contrib_data = [
        ["Metric", "Value"],
        ["Human authorship", f"{human_pct}%"],
        ["AI authorship",    f"{ai_pct}%"],
        ["Direction score",  f"{dir_score}%"],
        ["Methodology",      f"v{meth_version}"],
        ["Computed at",      computed_at],
    ]
    contrib_table = Table(contrib_data, colWidths=[80 * mm, 80 * mm])
    contrib_table.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, 0), _DARK),
        ("TEXTCOLOR",   (0, 0), (-1, 0), _BLUE),
        ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0), (-1, 0), 9),
        ("TEXTCOLOR",   (0, 1), (0, -1), _MUTED),
        ("TEXTCOLOR",   (1, 1), (1, -1), _WHITE),
        ("FONTSIZE",    (0, 1), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#18181B"), colors.HexColor("#1C1C1F")]),
        ("GRID",        (0, 0), (-1, -1), 0.3, colors.HexColor("#2D2D31")),
        ("TOPPADDING",  (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(contrib_table)
    story.append(Spacer(1, 5 * mm))

    # ── Section Authorship ────────────────────────────────────────────────────
    sections = song.get("sections", {})
    if sections:
        story.append(Paragraph("Section Authorship", h2))
        _SECTION_ORDER = ("verse_1", "chorus", "verse_2", "bridge", "outro")
        _SECTION_LABELS = {
            "verse_1": "Verse 1", "chorus": "Chorus", "verse_2": "Verse 2",
            "bridge": "Bridge",   "outro":  "Outro",
        }
        _PROV_LABELS = {
            "ai_generated":  "AI Generated",
            "human_written": "Human Written",
            "ai_then_human": "AI + Human Edit",
        }
        sec_data = [["Section", "Provenance", "Last Edited By"]]
        for sec_key in _SECTION_ORDER:
            if sec_key not in sections:
                continue
            sec  = sections[sec_key]
            prov = _PROV_LABELS.get(sec.get("provenance", ""), sec.get("provenance", "—"))
            by   = sec.get("last_edited_by", "—")
            sec_data.append([_SECTION_LABELS.get(sec_key, sec_key), prov, by])

        sec_table = Table(sec_data, colWidths=[45 * mm, 70 * mm, 45 * mm])
        sec_table.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (-1, 0), _DARK),
            ("TEXTCOLOR",   (0, 0), (-1, 0), _BLUE),
            ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",    (0, 0), (-1, 0), 9),
            ("TEXTCOLOR",   (0, 1), (-1, -1), _LIGHT),
            ("FONTSIZE",    (0, 1), (-1, -1), 8),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#18181B"), colors.HexColor("#1C1C1F")]),
            ("GRID",        (0, 0), (-1, -1), 0.3, colors.HexColor("#2D2D31")),
            ("TOPPADDING",  (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(sec_table)
        story.append(Spacer(1, 5 * mm))

    # ── Creative Timeline ─────────────────────────────────────────────────────
    story.append(Paragraph("Creative Timeline", h2))
    timeline = project.timeline or []
    if timeline:
        tl_data = [["#", "Event", "Actor", "Description", "Timestamp"]]
        for event in timeline:
            tl_data.append([
                str(event.get("seq", "?")),
                str(event.get("event_type", "")),
                str(event.get("actor", "")),
                str(event.get("description", ""))[:60],   # truncate long descriptions
                str(event.get("timestamp", ""))[:19],     # drop microseconds
            ])
        tl_table = Table(
            tl_data,
            colWidths=[8 * mm, 38 * mm, 18 * mm, 72 * mm, 34 * mm],
        )
        tl_table.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (-1, 0), _DARK),
            ("TEXTCOLOR",   (0, 0), (-1, 0), _BLUE),
            ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",    (0, 0), (-1, 0), 8),
            ("TEXTCOLOR",   (0, 1), (-1, -1), _LIGHT),
            ("FONTSIZE",    (0, 1), (-1, -1), 7),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#18181B"), colors.HexColor("#1C1C1F")]),
            ("GRID",        (0, 0), (-1, -1), 0.3, colors.HexColor("#2D2D31")),
            ("TOPPADDING",  (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("VALIGN",      (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(tl_table)
    else:
        story.append(Paragraph("No timeline events recorded.", muted))

    story.append(Spacer(1, 5 * mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=_MUTED))
    story.append(Spacer(1, 3 * mm))

    # ── Transparency Statement ────────────────────────────────────────────────
    story.append(Paragraph("Transparency Statement", h2))

    passport        = project.passport or {}
    custom_statement = passport.get("transparency_statement", "").strip()
    authorship_line  = passport.get("authorship_line", "").strip()

    statement_text = custom_statement or _DEFAULT_TRANSPARENCY.format(version=meth_version)
    story.append(Paragraph(statement_text, body))

    if authorship_line:
        story.append(Spacer(1, 3 * mm))
        story.append(Paragraph(authorship_line, ParagraphStyle(
            "auth", parent=styles["Normal"],
            fontSize=9, textColor=_GREEN, leading=13, fontName="Helvetica-Bold",
        )))

    # ── Footer ────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 5 * mm))
    watermark_id = passport.get("watermark_id", "—")
    story.append(Paragraph(
        f"Project ID: {project.project_id}  ·  "
        f"Watermark: {watermark_id}  ·  "
        f"Exported: {datetime.now().isoformat()[:19]}  ·  "
        f"HarmonyLedger v{project.version}",
        muted,
    ))

    doc.build(story)
    return buf.getvalue()
